import { Client, IntentsBitField, EmbedBuilder, PermissionsBitField, ActivityType, Channel, Message, Interaction, User, GuildMemberRoleManager, ChannelType, PermissionOverwrites, time } from "discord.js";

let createOracleEmbed = (header: string, text: string, fields: any[], link: string) => {
    const voidEmbed = new EmbedBuilder()
                .setColor('#1c3627')
                .setTitle(header)
                .setAuthor({ name: 'Oracle Foxhole Bot'})
                .setDescription(text)
                .setThumbnail('https://i.imghippo.com/files/GvV6040sj.png')
                .setTimestamp()
                .setFooter({ text: 'Message generated by Oracle Bot, forward any concerns to: pabelpanator', iconURL: 'https://i.imghippo.com/files/GvV6040sj.png' });
                
                if (fields){
                    for (let i = 0; i < fields.length; i++) {
                        voidEmbed.addFields({name: fields[i].name, value: fields[i].value});
                    }
                }

                if (link){
                    voidEmbed.setURL(link);
                }
                

    return voidEmbed;
};

export default createOracleEmbed